language: node_js
node_js:
  - "lts/*"
before_install:
  # installig az cli >
  # https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list  
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
  # < installig az cli
script: 
  - az --version
  - yarn test
  - yarn build
  # - az storage blob upload-batch -s public -d public --pattern *.html --content-type text/html

