language: node_js
node_js:
  - "lts/*"
before_install:
  # installig az cli >
  # https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list  
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
  - az login --service-principal -u $SP_NAME --password $SP_PASSWORD --tenant $SP_TENANT 
  # < installig az cli
script: 
  - az --version
  - yarn test
  - yarn build
  - az storage blob upload --file build/index.html --name index.html --container-name \$root --content-type text/html
  - az storage blob upload --file build/asset-manifest.json --name asset-manifest.json --container-name \$root --content-type application/json
  - az storage blob upload --file build/manifest.json --name manifest.json --container-name \$root --content-type application/json
  - az storage blob upload --file build/service-worker.js --name service-worker.js --container-name \$root --content-type application/javascript
  - az storage blob upload --file build/favicon.ico --name favicon.ico --container-name \$root --content-type image/x-icon
  - az storage blob upload-batch -s build/static -d static --pattern *.js --content-type application/javascript
  - az storage blob upload-batch -s build/static -d static --pattern *.css --content-type text/css
  - az storage blob upload-batch -s build/static -d static --pattern *.svg --content-type image/svg+xml
  - az storage blob upload-batch -s build/static -d static --pattern *.map --content-type application/json



